### ISSUE TITLE
placing a div between the input and the label break the styling

### ISSUE THREAD

**Issue by AdelElkhodary** [zellwk/adaptive-placeholders#7]
this is the how the markup made
> `<input type='text' class='form-control'>`
`<label class='label'>Email Address</label>`

but if i put a div between
> `<input type='text' class='form-control'>`
`<div class='error-message>Please write a valid email</div>'`
`<label class='label'>Email Address</label>`

then the styling will be broken 

i had to change that in the scss file all the `+ label ` to `~ label`
" From "
`.input {
 & + label {
    display: block;
    font-size: $font-size;
}`
" To"
`.input {
 & ~ label {
    display: block;
    font-size: $font-size;
}`

so i hope that you can fix that issue

Thank you

**Comment by AdelElkhodary** [comment]
I have added the pull request

**Comment by zellwk** [comment]
Done. Thanks for contributing! :)
